### ISSUE TITLE
LoginPath = new PathString("/Account/Login")

### ISSUE THREAD

**Issue by deepakAditi** [amd989/Owin.Security.Providers.PingFederate#1]
Basicaly I am new to OWIN,We need to implement the OWin with PingFederate,What is the above path ur reffereing too,,,I have Created the MVC Application ,What should I change according the above path...If I left it out as like you methioned, does it work...and Also where Do i configure the Landing Page URL

**Comment by amd989** [comment]
Hello,

I have added a sample application on how to use this library. Please refer to it to know how to configure it.

The path you mention has been added automatically by the default MVC template. It loads the login page so that you can choose the PingFederate as the external login provider.

Let me know if you need more assistance.

**Comment by deepakAditi** [comment]
Thankyou ..this helps
